'use strict';
const B=TrackBridge,P=TrackProject,$=id=>document.getElementById(id),state={files:[],models:[],lines:[],errors:[],generation:0,metadata:{},focus:true,busy:false,zoom:1,az:0,el:Math.PI/2};
const log=t=>{$('log').textContent+=t+'\n';$('log').scrollTop=$('log').scrollHeight;};
const status=t=>$('status').textContent=t;
const pause=()=>new Promise(r=>setTimeout(r,20));
const path=f=>(f.webkitRelativePath||f.name).replace(/\\/g,'/');
const json=v=>JSON.stringify(v,null,2);
function busy(v){state.busy=v;for(const id of ['folder','files','layout','load','scale','yaw','hidden','physics'])$(id).disabled=v;$('selection').querySelectorAll('input').forEach(e=>e.disabled=v);$('load').disabled=v||!state.files.some(f=>/\.kn5$/i.test(f.name));$('export').disabled=v||!state.models.length||!!state.errors.length;$('png').disabled=v||!state.models.length;$('report').disabled=v||!state.models.length;}
function clearModels(){state.models=[];state.lines=[];state.errors=[];state.metadata={};$('details').textContent='Конфигурация не прочитана.';$('report').disabled=true;$('export').disabled=true;$('png').disabled=true;stats();draw();}
async function choose(files){if(state.busy)return;state.generation++;state.files=Array.from(files).filter(f=>/\.(kn5|ini|ai|json)$/i.test(f.name));clearModels();$('log').textContent='';$('layout').replaceChildren(new Option('Ручной выбор моделей',''));for(const f of state.files.filter(f=>/^models.*\.ini$/i.test(f.name)))$('layout').append(new Option(path(f),path(f)));$('selection').replaceChildren();for(const f of state.files.filter(f=>/\.kn5$/i.test(f.name))){const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.checked=true;box.dataset.path=path(f);box.onchange=()=>{clearModels();status('Список изменён. Прочитайте модели заново.');};label.append(box,document.createTextNode(' '+path(f)+' ('+(f.size/1048576).toFixed(1)+' МБ)'));$('selection').append(label);}if($('layout').options.length>1){$('layout').selectedIndex=1;const preferred=Array.from($('layout').options).find(o=>/models_gp_2024\.ini$/i.test(o.value));if(preferred)$('layout').value=preferred.value;}busy(false);await applyLayout();log('Найдено файлов: '+state.files.length);status('Выберите конфигурацию и прочитайте модели.');}
async function plan(){const p=$('layout').value;if(!p)return null;const f=state.files.find(x=>path(x)===p);return B.parseModels(await f.text());}
function findModel(name){const audit=P.auditLayout([{file:name}],state.files.map(path),$('layout').value)[0];if(audit.status!=='ok')throw Error((audit.status==='missing'?'Отсутствует модель: ':'Неоднозначная модель: ')+name);return state.files.find(f=>path(f)===audit.matches[0]);}
async function applyLayout(){busy(true);clearModels();const generation=state.generation;try{const entries=await plan();if(generation!==state.generation)return;const audit=entries&&P.auditLayout(entries,state.files.map(path),$('layout').value);const issues=(audit||[]).filter(a=>a.status!=='ok');const selected=audit&&audit.flatMap(x=>x.matches);if(issues.length){log('Конфигурация некомплектна: '+issues.map(x=>x.file+' ('+x.status+')').join(', '));status('Не хватает файлов конфигурации. Выберите другую конфигурацию или ручной режим.');}$('selection').querySelectorAll('input').forEach(x=>x.checked=!selected||selected.includes(x.dataset.path));}catch(e){log('Конфигурация: '+e.message);status(e.message);}finally{busy(false);}}
$('folder').onchange=e=>choose(e.target.files);$('files').onchange=e=>choose(e.target.files);$('layout').onchange=applyLayout;
$('load').onclick=async()=>{busy(true);clearModels();$('log').textContent='';try{const entries=await plan();const chosen=Array.from($('selection').querySelectorAll('input:checked')).map(x=>x.dataset.path);if(!chosen.length)throw Error('Выберите хотя бы одну модель');let jobs;if(entries){jobs=entries.map(e=>({file:findModel(e.file),position:e.position})).filter(x=>chosen.includes(path(x.file)));const known=new Set(jobs.map(x=>path(x.file)));for(const p of chosen)if(!known.has(p))jobs.push({file:state.files.find(f=>path(f)===p),position:[0,0,0]});}else jobs=chosen.map(p=>({file:state.files.find(f=>path(f)===p),position:[0,0,0]}));
const total=jobs.reduce((s,x)=>s+x.file.size,0);if(total>512*1024*1024)throw Error('Выбрано более 512 МБ KN5. Обрабатывайте модели отдельными пакетами.');
for(let i=0;i<jobs.length;i++){const j=jobs[i];status('Чтение '+(i+1)+'/'+jobs.length+': '+j.file.name);await pause();try{const model=B.parseKn5(await j.file.arrayBuffer());state.models.push({name:j.file.name,source:path(j.file),size:j.file.size,position:j.position,model});log('OK '+j.file.name+': '+model.meshes.length+' мешей');for(const w of model.warnings)log('Замечание: '+w);}catch(e){state.errors.push(j.file.name+': '+e.message);log('ОШИБКА '+state.errors.at(-1));}}
const cfg=selectedConfig(),aiFiles=state.files.filter(f=>/^(fast|pit)_lane\.ai$/i.test(f.name));for(const f of aiFiles){if(cfg.ini&&P.normalizedPath(path(f))!==P.normalizedPath(cfg.base+(cfg.layout?cfg.layout+'/':'')+'ai/'+f.name))continue;try{if(f.size>128*1024*1024)throw Error('AI больше 128 МБ');const line=B.parseAi(await f.arrayBuffer());state.lines.push({name:f.name,source:path(f),...line});log('AI '+path(f)+': '+line.points.length+' точек. Только координаты; хвост '+line.ignoredBytes+' байт не перенесён.');}catch(e){log('AI пропущен: '+path(f)+': '+e.message);}}
await readMetadata();state.zoom=1;state.focus=true;stats();draw();status(state.errors.length?'Есть ошибки моделей — экспорт заблокирован. Уберите проблемные файлы и повторите.':'Готово к экспорту пакета подготовки.');if(!state.lines.length)log('AI-линии не загружены. Без них пакет содержит только геометрию.');log('F1M24: адаптер игровой трассы отсутствует. Результат нельзя установить в игру.');
}catch(e){state.errors.push(e.message);status(e.message);log(e.message);}finally{busy(false);}};
function options(){const scale=Number($('scale').value),yaw=Number($('yaw').value);if(!Number.isFinite(scale)||scale<=0||scale>10000||!Number.isFinite(yaw))throw Error('Проверьте масштаб и поворот');return {scale,yaw,includeHidden:$('hidden').checked,collision:$('physics').checked};}
function download(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
$('export').onclick=async()=>{busy(true);try{const opts=options(),entries=[],manifest={application:'AC TrackBridge',version:'0.2',stage:'intermediate_assets_only',installable_in_f1m24:false,coordinateMapping:'AC(x,y,z) -> (x,z,y), then yaw around Z, then uniform scale',options:opts,layout:$('layout').value,models:[],ai:[],sourceMetadata:state.metadata,blockers:['F1M24 track schema and runtime references not implemented','Game race/pit/overtaking/DRS/sector data not generated','Game level, materials and collision not authored','No cooking, PAK/IoStore generation or in-game validation']};
Object.assign(manifest,{schemaVersion:1,installable:false,target:'F1 Manager 2024',transform:{axisMap:'x,z,y',scale:opts.scale,yaw:opts.yaw},sourceUnits:'metres',coordinateUnits:opts.scale===100?'centimetres':'source metres multiplied by scale',markers:state.metadata.markers||[],timingGates:state.metadata.timingGates||[],drs:state.metadata.drs||[],surfaces:state.metadata.surfaces||[],sourceTrack:state.metadata.sourceTrack||null,lines:[],transformedMarkers:(state.metadata.markers||[]).map(a=>({name:a.name,source:a.source,position:B.mapPoint(a.position,opts)}))});
const lineNames=new Set();for(const line of state.lines){const name=line.name.toLowerCase();if(lineNames.has(name))throw Error('Duplicate AI line: '+name+'. Select one layout.');lineNames.add(name);}
for(let i=0;i<state.models.length;i++){status('Экспорт модели '+(i+1)+'/'+state.models.length);await pause();const m=state.models[i],dir='models/'+i+'_'+B.safeName(m.name.replace(/\.kn5$/i,''))+'/',mat=B.materialExport(m.model);
entries.push({name:dir+'model.obj',data:await objBytes(m.model,opts,m.position)},{name:dir+'model.mtl',data:mat.text},{name:dir+'materials.json',data:json(m.model.materials)});m.model.textures.forEach((t,k)=>entries.push({name:dir+mat.paths[k],data:t.data}));
if(opts.collision&&m.model.meshes.some(x=>B.shouldExportMesh(x,{mode:'collision'})))entries.push({name:dir+'collision.obj',data:await objBytes(m.model,{...opts,mode:'collision'},m.position)});
entries.push({name:dir+'anchors.json',data:json(m.model.anchors.map(a=>({name:a.name,active:a.active,sourceMatrix:a.matrix,position:B.mapPoint(a.position.map((v,j)=>v+m.position[j]),opts)})))});
manifest.models.push({source:m.source,sourceBytes:m.size,position:m.position,output:dir+'model.obj',meshes:m.model.meshes.map(x=>({name:x.name,material:x.material,layer:x.layer,lod:x.lod,active:x.active,visible:x.visible,renderable:x.renderable,exported:opts.includeHidden||!!(x.active&&x.visible&&x.renderable)})),warnings:m.model.warnings});}
for(let i=0;i<state.lines.length;i++){const l=state.lines[i],name='lines/'+B.safeName(l.name.toLowerCase())+'.csv';entries.push({name,data:'index,x,y,z,source_distance_m,source_id\n'+l.points.map((p,k)=>[k,...B.mapPoint(p.p,opts),p.distance,p.id].join(',')).join('\n')+'\n'});manifest.lines.push({source:l.source,csv:name,...P.lineStats(l.points),ignoredBytes:l.ignoredBytes});manifest.ai.push({source:l.source,output:name,points:l.points.length,ignoredBytes:l.ignoredBytes,statistics:P.lineStats(l.points),note:'Coordinates only. Not F1M24 race data. No closure or resampling applied.'});}
entries.push({name:'trackbridge-project.json',data:json(manifest)},{name:'READ_ME_FIRST.txt',data:'ПАКЕТ ПОДГОТОВКИ — НЕ ГОТОВЫЙ МОД F1 MANAGER 24\n\ncollision.obj содержит физические поверхности AC (активные меши с числовым префиксом). Это исходная геометрия для настройки коллизии, не готовая коллизия Unreal. Не включайте её видимость поверх model.obj.\n\nOBJ/MTL можно открыть в DCC-редакторе (например Blender). Исходные DDS-текстуры могут требовать преобразования для конкретного импортёра. AC-шейдеры не воспроизводятся; параметры сохранены в materials.json.\n\nКоординаты по умолчанию в сантиметрах: X=AC X, Y=AC Z, Z=AC Y. Применён выбранный поворот. UV V инвертирован для OBJ. Имена AC_START, AC_PIT и других узлов находятся в anchors.json. Это ориентиры AC, а не игровые объекты F1M24.\n\nДля готовой трассы необходимы: проверенный адаптер данных F1M24; игровые траектории, пит-лейн и гоночные параметры; материалы и коллизия; ссылки уровня; cooking совместимой версией движка; сборка и проверка в игре. Программа эти шаги не выполняет.\n\nНе копируйте этот ZIP в папку Paks. Все исходные файлы остались неизменными.\n'});
status('Сборка ZIP…');await pause();download(B.zip(entries),'TrackBridge_Preparation.zip');status('Пакет подготовки скачан. Это не установочный мод.');}catch(e){status('Экспорт не выполнен: '+e.message);log(e.stack||e.message);}finally{busy(false);}};
function stats(){$('nmodels').textContent=state.models.length;$('nmeshes').textContent=state.models.reduce((s,m)=>s+m.model.meshes.length,0).toLocaleString();$('ntri').textContent=state.models.reduce((s,m)=>s+m.model.meshes.reduce((a,n)=>a+n.indices.length/3,0),0).toLocaleString();$('npoints').textContent=state.lines.reduce((s,l)=>s+l.points.length,0).toLocaleString();state.cache=null;}
function cache(){if(state.cache)return state.cache;const meshes=[],lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];let triangles=0;for(const item of state.models)for(const m of item.model.meshes){if(!$('hidden').checked&&(!m.active||!m.visible||!m.renderable))continue;meshes.push({m,offset:item.position});triangles+=m.indices.length/3;for(let i=0;i<m.positions.length;i+=3)for(let j=0;j<3;j++){const v=m.positions[i+j]+item.position[j];lo[j]=Math.min(lo[j],v);hi[j]=Math.max(hi[j],v);}}if(state.focus&&state.lines.some(l=>/^fast_lane\.ai$/i.test(l.name))){lo.fill(Infinity);hi.fill(-Infinity);for(const l of state.lines.filter(l=>/^(fast|pit)_lane\.ai$/i.test(l.name)))for(const p of l.points)for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],p.p[j]);hi[j]=Math.max(hi[j],p.p[j]);}}const center=lo.map((v,i)=>Number.isFinite(v)?(v+hi[i])/2:0),extent=Math.max(1,...lo.map((v,i)=>Number.isFinite(v)?hi[i]-v:1));state.cache={meshes,center,extent,triangles};return state.cache;}
function draw(){const canvas=$('view'),dpr=Math.min(window.devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#101720';ctx.fillRect(0,0,w,h);const c=cache(),sc=Math.min(w,h)*.82/c.extent*state.zoom,ca=Math.cos(state.az),sa=Math.sin(state.az),ce=Math.cos(state.el),se=Math.sin(state.el);function project(p){const x=p[0]-c.center[0],y=p[2]-c.center[2],z=p[1]-c.center[1],u=x*ca-y*sa,v=x*sa+y*ca;return [w/2+u*sc,h/2+(v*se-z*ce)*sc];}const step=Math.max(1,Math.ceil(c.triangles/40000));for(const {m,offset} of c.meshes){ctx.strokeStyle=/ROAD|ASPH|KERB|CURB|TRACK/i.test(m.name)?'#65dcb6':'#405c79';ctx.lineWidth=.6;ctx.beginPath();for(let k=0;k<m.indices.length;k+=3*step){for(let j=0;j<3;j++){const i=m.indices[k+j]*3,p=project([m.positions[i]+offset[0],m.positions[i+1]+offset[1],m.positions[i+2]+offset[2]]);j?ctx.lineTo(...p):ctx.moveTo(...p);}ctx.closePath();}ctx.stroke();}for(const l of state.lines){ctx.strokeStyle=/pit/i.test(l.name)?'#ffcb72':'#ff668a';ctx.lineWidth=2;ctx.beginPath();l.points.forEach((p,i)=>{const q=project(p.p);i?ctx.lineTo(...q):ctx.moveTo(...q);});ctx.stroke();}if(!state.models.length){ctx.fillStyle='#98abc2';ctx.font='16px system-ui';ctx.textAlign='center';ctx.fillText('Выберите трассу и нажмите «Прочитать»',w/2,h/2);}}
$('top').onclick=()=>{state.az=0;state.el=Math.PI/2;draw();};$('iso').onclick=()=>{state.az=-.7;state.el=.6;draw();};$('fit').onclick=()=>{state.focus=false;state.cache=null;state.zoom=1;draw();};$('focus').onclick=()=>{state.focus=true;state.cache=null;state.zoom=1;draw();};$('hidden').onchange=()=>{state.cache=null;draw();};let drag=null;$('view').onpointerdown=e=>{drag=[e.clientX,e.clientY];e.target.setPointerCapture(e.pointerId);};$('view').onpointermove=e=>{if(!drag)return;state.az+=(e.clientX-drag[0])*.008;state.el=Math.max(-1.57,Math.min(1.57,state.el+(e.clientY-drag[1])*.008));drag=[e.clientX,e.clientY];draw();};$('view').onpointerup=$('view').onpointercancel=()=>drag=null;$('view').addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.1,Math.min(30,state.zoom*Math.exp(-e.deltaY*.001)));draw();},{passive:false});window.onresize=draw;
$('png').onclick=()=>{const az=state.az,el=state.el;state.az=0;state.el=Math.PI/2;draw();$('view').toBlob(b=>{if(b)download(b,'TrackBridge_top_view.png');},'image/png');state.az=az;state.el=el;draw();};draw();

async function objBytes(model,opts,position){const parts=[];let n=0;for(const chunk of B.exportObjChunks(model,opts,position)){parts.push(new TextEncoder().encode(chunk));if(++n%32===0)await pause();}return new Uint8Array(await new Blob(parts).arrayBuffer());}
function selectedConfig(){const ini=$('layout').value;return {ini,base:ini.includes('/')?ini.slice(0,ini.lastIndexOf('/')+1):'',layout:ini.split('/').pop().replace(/^models_?/i,'').replace(/\.ini$/i,'')};}
async function readMetadata(){const cfg=selectedConfig(),out={target:'F1 Manager 2024',installable:false,layout:cfg.layout,sourceTrack:null,drs:[],surfaces:[],timingGates:[],markers:[],lines:[]};
 async function textAt(relative){const wanted=P.normalizedPath(cfg.base+relative),matches=state.files.filter(f=>P.normalizedPath(path(f))===wanted);return matches.length===1?await matches[0].text():null;}
 const dataPrefix=cfg.layout?cfg.layout+'/data/':'data/';try{const ui=await textAt(cfg.layout?'ui/'+cfg.layout+'/ui_track.json':'ui/ui_track.json');if(ui)out.sourceTrack=JSON.parse(ui.replace(/^\uFEFF/,''));}catch(e){log('ui_track.json: '+e.message);}
 try{const drs=await textAt(dataPrefix+'drs_zones.ini');if(drs)out.drs=P.drsZones(drs);}catch(e){log(e.message);}
 const surface=await textAt(dataPrefix+'surfaces.ini');if(surface)out.surfaces=P.parseIni(surface);
 for(const item of state.models)for(const a of item.model.anchors)if(a.active&&/^AC_/.test(a.name))out.markers.push({name:a.name,source:item.source,position:a.position.map((v,j)=>v+item.position[j]),matrixAC:a.matrix});
 out.timingGates=P.timingGates(out.markers);out.lines=state.lines.map(l=>({source:l.source,name:l.name,...P.lineStats(l.points)}));state.metadata=out;
 const race=out.lines.find(x=>/^fast_lane\.ai$/i.test(x.name)),start=out.markers.filter(x=>/^AC_START_\d+$/.test(x.name)),pit=out.markers.filter(x=>/^AC_PIT_\d+$/.test(x.name));
 $('details').textContent=[out.sourceTrack?.name||cfg.layout||'Ручной выбор','Цель: F1 Manager 2024','Длина из описания AC: '+(out.sourceTrack?.length||'нет')+' м',race?'Замкнутая AI-линия: '+race.lengthWithClosingSegmentM.toFixed(2)+' м; зазор концов '+race.endpointGapM.toFixed(2)+' м':'AI-линия не найдена','Стартовые позиции: '+start.length+'; пит-позиции: '+pit.length,'Пары тайминга: '+out.timingGates.length+'; зоны DRS AC: '+out.drs.length,'Поверхности AC: '+out.surfaces.length,'Это исходные данные AC. Перенос правил гонки в F1M24 не выполнен.'].join('\n');
 if(race&&Number(out.sourceTrack?.length)>0&&Math.abs(Number(out.sourceTrack.length)-race.lengthWithClosingSegmentM)>10)log('Длина из описания и длина AI-линии различаются; автоматически они не подменяются.');
 const n=state.models.reduce((sum,x)=>sum+x.model.meshes.filter(m=>m.active&&!m.renderable&&/^\d+[_a-z]/i.test(m.name)).length,0);if(n)log('Найдено невидимых физических мешей: '+n+'. Экспортируйте отдельный collision.obj.');
}
$('report').onclick=()=>download(new Blob([json(state.metadata)],{type:'application/json'}),'TrackBridge_source_report.json');
