#!/usr/bin/env node
/* Optional sequential exporter. Node.js 18+. Browser app does not need Node.js. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),B=require('./core.js'),P=require('./project.js');
function args(argv){const o={layout:'models_gp_2024.ini',scale:100,yaw:0};for(let i=0;i<argv.length;i++){const a=argv[i];if(a==='--report-only'||a==='--no-textures'){o[a.slice(2)]=true;continue;}if(!['--track','--layout','--out','--scale','--yaw'].includes(a))throw Error('Unknown option '+a);if(i+1>=argv.length)throw Error('Missing value '+a);o[a.slice(2)]=argv[++i];}o.scale=Number(o.scale);o.yaw=Number(o.yaw);if(!(o.scale>0)||!Number.isFinite(o.scale)||!Number.isFinite(o.yaw))throw Error('Invalid transform');if(!o.track||!o.out)throw Error('Usage: node convert.js --track TRACK_FOLDER --layout models_gp_2024.ini --out NEW_OUTPUT_FOLDER [--report-only] [--no-textures]');return o;}
function main(){const o=args(process.argv.slice(2)),root=fs.realpathSync(o.track),dest=path.resolve(o.out),tmp=dest+'.partial';if(fs.existsSync(dest)||fs.existsSync(tmp))throw Error('Output or .partial folder already exists; choose a new output path');if(dest===root||root.startsWith(dest+path.sep))throw Error('Output must not be an ancestor of source');const safeSource=relative=>{const p=path.resolve(root,relative);const inside=x=>{const rel=path.relative(root,x);return rel!==''&&!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel);};if(!inside(p))throw Error('Source outside track folder');if(fs.existsSync(p)&&!inside(fs.realpathSync(p)))throw Error('Source symlink outside track folder');return p;};const ini=safeSource(o.layout);const sourceBase=path.dirname(o.layout);const jobs=B.parseModels(fs.readFileSync(ini,'utf8')).map(j=>({...j,file:path.join(sourceBase,j.file)}));if(!jobs.length)throw Error('Layout contains no MODEL entries');
for(const j of jobs)if(!fs.existsSync(safeSource(j.file)))throw Error('Missing model: '+j.file+' (nothing exported)');
const layout=path.basename(o.layout).replace(/^models_?/i,'').replace(/\.ini$/i,'');fs.mkdirSync(tmp,{recursive:true});const manifest={application:'AC TrackBridge',version:'0.2',target:'F1 Manager 2024',installable:false,layout,reportOnly:!!o['report-only'],transform:{axisMap:'x,z,y',scale:o.scale,yaw:o.yaw},sourceUnits:'metres',coordinateUnits:o.scale===100?'centimetres':'source metres multiplied by scale',models:[],markers:[],timingGates:[],lines:[],drs:[],surfaces:[],warnings:[],blockers:['F1M24 race-data adapter not implemented','Game track and dependencies unavailable for cooking','No game package produced or tested']};
const write=(relative,data)=>{const p=path.join(tmp,relative);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,data);};const writeJSON=(p,x)=>write(p,JSON.stringify(x,null,2));let index=0;
for(const job of jobs){console.log('Model '+(++index)+'/'+jobs.length+': '+job.file);const source=safeSource(job.file),b=fs.readFileSync(source),model=B.parseKn5(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)),dir='models/'+index+'_'+B.safeName(path.basename(job.file,'.kn5')),opts={scale:o.scale,yaw:o.yaw};
const visual=model.meshes.filter(m=>B.shouldExportMesh(m)),physics=model.meshes.filter(m=>B.shouldExportMesh(m,{mode:'collision'}));const info={source:job.file,sourceBytes:b.length,version:model.version,position:job.position,vertices:model.meshes.reduce((s,m)=>s+m.positions.length/3,0),triangles:model.meshes.reduce((s,m)=>s+m.indices.length/3,0),meshes:model.meshes.length,visualMeshes:visual.length,physicsMeshes:physics.length,visualTriangles:visual.reduce((s,m)=>s+m.indices.length/3,0),physicsTriangles:physics.reduce((s,m)=>s+m.indices.length/3,0),textures:model.textures.length,warnings:model.warnings,exports:[]};
if(!o['report-only']){const exportOBJ=(name,mode)=>{const destFile=path.join(tmp,dir,name);fs.mkdirSync(path.dirname(destFile),{recursive:true});const fd=fs.openSync(destFile,'wx');try{for(const chunk of B.exportObjChunks(model,{...opts,mode},job.position))fs.writeFileSync(fd,chunk);}finally{fs.closeSync(fd);}info.exports.push(dir+'/'+name);};if(visual.length)exportOBJ('model.obj','visual');if(physics.length)exportOBJ('collision.obj','collision');const mat=B.materialExport(model);write(dir+'/model.mtl',mat.text);writeJSON(dir+'/materials.json',model.materials);if(!o['no-textures'])model.textures.forEach((t,k)=>write(dir+'/'+mat.paths[k],t.data));else manifest.warnings.push(job.file+': textures intentionally omitted');}
const anchors=model.anchors.filter(a=>a.active&&/^AC_/.test(a.name)).map(a=>({name:a.name,source:job.file,position:a.position.map((v,k)=>v+job.position[k]),matrixAC:a.matrix}));manifest.markers.push(...anchors);manifest.models.push(info);if(global.gc)global.gc();}
const configPrefix=path.join(sourceBase,layout) + path.sep;for(const name of ['fast_lane.ai','pit_lane.ai']){const rel=configPrefix+'ai/'+name,p=safeSource(rel);if(!fs.existsSync(p)){manifest.warnings.push('Missing '+rel);continue;}const b=fs.readFileSync(p),l=B.parseAi(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)),stats=P.lineStats(l.points),csv='lines/'+name+'.csv';write(csv,'index,x,y,z,source_distance_m,source_id\n'+l.points.map((x,i)=>[i,...B.mapPoint(x.p,o),x.distance,x.id].join(',')).join('\n')+'\n');manifest.lines.push({source:rel,csv,...stats,ignoredBytes:l.ignoredBytes});}
for(const [filename,key,parser] of [['drs_zones.ini','drs',P.drsZones],['surfaces.ini','surfaces',P.parseIni]]){const p=safeSource(configPrefix+'data/'+filename);if(fs.existsSync(p))manifest[key]=parser(fs.readFileSync(p,'utf8'));}
const ui=safeSource(path.join(sourceBase,layout?'ui/'+layout+'/ui_track.json':'ui/ui_track.json'));if(fs.existsSync(ui))manifest.sourceTrack=JSON.parse(fs.readFileSync(ui,'utf8').replace(/^\uFEFF/,''));manifest.timingGates=P.timingGates(manifest.markers);manifest.transformedMarkers=manifest.markers.map(a=>({name:a.name,source:a.source,position:B.mapPoint(a.position,o)}));
writeJSON('trackbridge-project.json',manifest);write('README.txt','Intermediate Assetto Corsa assets for F1 Manager 2024 research. NOT AN INSTALLABLE MOD.\n\nmodel.obj = visible geometry; collision.obj = AC physical mesh candidates (numeric prefixes), not cooked Unreal collision. Keep collision meshes invisible. Source shader reconstruction, race-data conversion, game level authoring, cooking and validation remain undone.\n\nCSV and transformedMarkers use selected coordinate transform. markers, timingGates and line statistics remain AC metres. DRS values remain original normalized AC positions.\n\nDo not install this directory into Paks.\n');fs.renameSync(tmp,dest);console.log('Export complete: '+dest+'\nNOT an installable F1M24 mod.');}
try{main();}catch(e){console.error(e.stack||e);process.exitCode=1;}
