/* Intermediate project metadata only. Does not implement F1M24 race data. */
(function(root){'use strict';
function parseIni(text){const out=[];let s=null;for(const raw of text.replace(/^\uFEFF/,'').split(/\r?\n/)){const line=raw.trim();if(!line||/^[;#]/.test(line))continue;const h=line.match(/^\[([^\]]+)\]/);if(h){s={section:h[1],values:{}};out.push(s);}else if(s){const i=line.indexOf('=');if(i>=0)s.values[line.slice(0,i).trim().toUpperCase()]=line.slice(i+1).trim();}}return out;}
function lineStats(points){let length=0;const cumulative=[0],lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<points.length;i++){const p=points[i].p;if(p.length!==3||!p.every(Number.isFinite))throw Error('Некорректная точка линии');for(let j=0;j<3;j++){lo[j]=Math.min(lo[j],p[j]);hi[j]=Math.max(hi[j],p[j]);}if(i){length+=Math.hypot(...p.map((x,j)=>x-points[i-1].p[j]));cumulative.push(length);}}const gap=points.length>1?Math.hypot(...points[0].p.map((x,j)=>x-points.at(-1).p[j])):0;return {pointCount:points.length,polylineLengthM:length,endpointGapM:gap,lengthWithClosingSegmentM:length+gap,cumulativeDistanceM:cumulative,bounds:{min:lo,max:hi}};}
function drsZones(text){return parseIni(text).filter(x=>/^ZONE_\d+$/i.test(x.section)).map(s=>{const out={name:s.section,sourceValues:s.values};for(const k of ['DETECTION','START','END']){const v=Number(s.values[k]);if(s.values[k]===undefined||s.values[k].trim()===''||!Number.isFinite(v)||v<0||v>1)throw Error('DRS: '+s.section+' / '+k+' должно быть 0…1');out[k.toLowerCase()]=v;}out.wrapsStartFinish=out.end<out.start;return out;});}
function timingGates(anchors){const timingNames=new Set();for(const a of anchors)if(/^AC_TIME_\d+_[LR]$/.test(a.name)){if(timingNames.has(a.name))throw Error('Duplicate timing marker: '+a.name);timingNames.add(a.name);if(!Array.isArray(a.position)||a.position.length!==3||!Array.from(a.position).every(Number.isFinite))throw Error('Invalid timing marker: '+a.name);}const names=new Map(anchors.map(x=>[x.name,x]));const out=[];for(const a of anchors){const m=a.name.match(/^AC_TIME_(\d+)_L$/);if(!m)continue;const b=names.get('AC_TIME_'+m[1]+'_R');if(b)out.push({index:Number(m[1]),left:a.position,right:b.position,midpoint:a.position.map((v,i)=>(v+b.position[i])/2),source:'AC timing markers, not F1M24 sector data'});}return out.sort((a,b)=>a.index-b.index);}
function normalizedPath(p){return p.replace(/\\/g,'/').replace(/^\.\//,'').toLowerCase();}
function auditLayout(entries,paths,iniPath=''){const base=iniPath.includes('/')?iniPath.slice(0,iniPath.lastIndexOf('/')+1):'';return entries.map(e=>{const wanted=normalizedPath(base+e.file);let matches=paths.filter(p=>normalizedPath(p)===wanted);if(!matches.length)matches=paths.filter(p=>normalizedPath(p)===normalizedPath(e.file)||normalizedPath(p).endsWith('/'+normalizedPath(e.file)));return {file:e.file,position:e.position,rotation:e.rotation,status:matches.length===1?'ok':matches.length?'ambiguous':'missing',matches};});}
const api={normalizedPath,parseIni,lineStats,drsZones,timingGates,auditLayout};if(typeof module!=='undefined')module.exports=api;else root.TrackProject=api;
})(globalThis);
